eureka:
  instance:
    preferIpAddress: true #registra IP ao inves do nome
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/