server:
  port: 8761

eureka:
  client:
    registerWithEureka: false # tells the service not to register with a Eureka when application starts because this is the Eureka service
    fetchRegistry: false # dont cache registry information locally
  server:
      waitTimeInMsWhenSyncEmpty: 5