server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunosc/config-repo-ms-in-action/
          searchPaths: licensingservice,organizationservice,zuulservice,authenticationservice